#!/bin/bash

# Augment Jira Tickets with Technical Implementation Plans
# This script uses Bob in non-interactive mode to analyze new tickets
# and add detailed technical comments for coding agents

set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🤖 Jira Ticket Augmentation Script${NC}"
echo -e "${BLUE}=====================================${NC}\n"

# Configuration
JIRA_PROJECT_KEY="AUT"
JIRA_STATUS_FILTER="To Do"

# Check if Bob is available
if ! command -v bob &> /dev/null; then
    echo -e "${RED}❌ Error: Bob Shell is not installed or not in PATH${NC}"
    echo -e "${YELLOW}Please install Bob Shell first${NC}"
    exit 1
fi

echo -e "${BLUE}📋 Fetching new tickets from Jira project: ${JIRA_PROJECT_KEY}${NC}\n"

# Create a temporary file for the Bob prompt
PROMPT_FILE=$(mktemp)

# Build the prompt for Bob
cat > "$PROMPT_FILE" << 'EOF'
You are a technical architect analyzing Jira tickets to create detailed implementation plans for coding agents.

TASK:
1. Use the Jira MCP server to fetch all tickets in the "AUT" project with status "To Do"
2. For each ticket found, analyze the codebase context and create a detailed technical implementation plan
3. Add the implementation plan as a comment to the ticket using the Jira MCP server

CODEBASE CONTEXT:
- Backend: Python FastAPI application in bob-shell-demo/python_backend/
  - Models: app/models.py (User, Flight, Booking)
  - Schemas: app/schemas.py (Pydantic validation)
  - Main API: app/main.py (FastAPI endpoints)
  - Database: SQLite with SQLAlchemy ORM
  
- Frontend: React TypeScript application in bob-shell-demo/frontend/
  - Registration: src/components/customer/RegistrationModal.tsx
  - API Client: src/api/client.ts and src/api/endpoints.ts
  - Types: src/types/index.ts
  - Hooks: src/hooks/useUser.ts

IMPLEMENTATION PLAN FORMAT:
Create a detailed comment with the following sections:

## 🎯 Technical Implementation Plan

### Backend Changes Required:

#### 1. Database Schema Update
- File: `python_backend/app/models.py`
- Changes: [Specific model changes needed]
- Migration considerations: [Any data migration needed]

#### 2. API Schema Update
- File: `python_backend/app/schemas.py`
- Changes: [Pydantic schema updates]
- Validation rules: [New validation requirements]

#### 3. API Endpoint Updates
- File: `python_backend/app/main.py`
- Endpoints to modify: [List specific endpoints]
- New fields to handle: [Field details]

### Frontend Changes Required:

#### 4. TypeScript Types
- File: `frontend/src/types/index.ts`
- New interfaces/types: [Type definitions needed]

#### 5. API Client Updates
- File: `frontend/src/api/endpoints.ts`
- Changes: [API call modifications]

#### 6. Component Updates
- File: `frontend/src/components/customer/RegistrationModal.tsx`
- UI Changes: [Form field additions]
- Validation: [Client-side validation logic]

#### 7. Hooks Updates
- File: `frontend/src/hooks/useUser.ts`
- Changes: [Hook modifications if needed]

### Testing Requirements:
- Backend tests to add/update
- Frontend validation tests
- Integration test scenarios

### Deployment Considerations:
- Database migration steps
- Backward compatibility
- Environment variable updates

### Estimated Complexity: [Low/Medium/High]
### Estimated Time: [X hours/days]

---
*Generated by Bob Shell Automation*

IMPORTANT: 
- Use actual file paths from the codebase
- Reference specific line numbers where changes are needed
- Include code snippets for complex changes
- Be specific about validation rules and error handling
- Consider edge cases and error scenarios

Now execute this task using the MCP servers.
EOF

echo -e "${YELLOW}🔍 Analyzing tickets and generating implementation plans...${NC}\n"

# Run Bob in non-interactive mode with the prompt
bob --yolo -p "$(cat $PROMPT_FILE)" 2>&1 | tee /tmp/bob-augment-output.log

# Check if Bob execution was successful
if [ ${PIPESTATUS[0]} -eq 0 ]; then
    echo -e "\n${GREEN}✅ Successfully augmented Jira tickets with implementation plans${NC}"
    echo -e "${GREEN}📝 Full output saved to: /tmp/bob-augment-output.log${NC}"
else
    echo -e "\n${RED}❌ Error occurred during ticket augmentation${NC}"
    echo -e "${YELLOW}Check /tmp/bob-augment-output.log for details${NC}"
    exit 1
fi

# Cleanup
rm -f "$PROMPT_FILE"

echo -e "\n${BLUE}=====================================${NC}"
echo -e "${GREEN}🎉 Ticket augmentation complete!${NC}"
echo -e "${BLUE}View your tickets at: https://adityakrishnan28.atlassian.net/jira/software/projects/${JIRA_PROJECT_KEY}/boards${NC}\n"

# Made with Bob
